### ISSUE TITLE
How do i set git-bash.exe in environment path ?

### ISSUE THREAD

**Issue by morwin10** [Robert923/vscode-start-git-bash#1]
I have git bash in my computer, and i did this: (img 2)

![git_bash_properties](https://cloud.githubusercontent.com/assets/3899222/17504273/2a9ecd32-5e00-11e6-8b6c-d4fc4c650ebd.PNG)
![env_path](https://cloud.githubusercontent.com/assets/3899222/17504277/2c690240-5e00-11e6-92e4-9d55e40aa097.PNG)

But it doesn't work, I get this error:

`Failed to start bash - is git-bash.exe on the system path?`

I'm not sure i did it well so please help me how i can do it

Thanks!

**Comment by Robert923** [comment]
You're very close!
In the environment variable "Edit User Variable" don't include git-bash.exe.
Instead, just put the folder.   So in your case you just want the "C:\Program Files\Git\" portion (without the quotes).

I hope that helps,

Robert

**Comment by anthonyguertin** [comment]
I wasted a lot of time on this... more than I should have. Thank you Robert923.

**Comment by leotm** [comment]
You may find this handy too in future!

https://patheditor2.codeplex.com/

And don't forgot to close issue @morwin10  :D

**Comment by Robert923** [comment]
I'm going to close this given that I think we've solved it and the OP hasn't responded in months.

**Comment by yongli-abc** [comment]
Thanks Robert923.

FYI, another pitfall that cost me a few minutes: you need to restart vscode after editing the environment variables, otherwise it wont' be picked up.

**Comment by hanabichang** [comment]
Thanks！

**Comment by KaKi87** [comment]
Hello,

I tried to replace `cmd.exe` by `C:\\Program Files\\Git\\bin\\bash.exe` and eDEX wouldn't start anymore.

I also tried a symbolic link at `C:\` but didn't worked either.

I had to add the folder to my PATH environment variable instead to make it work.

I think that not being able to specify an absolute path is an issue.

Thanks
