### ISSUE TITLE
Second command for stating bash in project root

### ISSUE THREAD

**Issue by mlewand** [Robert923/vscode-start-git-bash#6]
I think it would be nice also to add a command to open bash in project root despite of the context.

I often find myself in a need to quickly open git bash in main dir, but for instance I'm editing `generator/app/index.js` file. Currently I need to do some extra steps to get into main directory.

It would be nice to have another command by side to the existing one (whichi is super useful too if you want to do stuff with the cur file).

It would also allow to bind two separate hotkeys to both of the files.

Let me know if you'd simply wish to see it here, I'm willing to send a pull request if you're interested in this.

**Comment by Robert923** [comment]
Excellent point - I can't add it tonight but will be able to this week.

**Comment by mlewand** [comment]
As I said, I'm willing help you with this. I can create a PR for you if you want me to, it will make things easier to you. :)

**Comment by Robert923** [comment]
If you want it faster, sure.  :-)
I've tried to keep the code clean and well documented, so it should be easy to make the change.
